"""
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is 
not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and 
D = |Pk − Pj| is minimised; what is the value of D?
"""

pentagonal = [n*(3*n-1)//2 for n in range(1,10001)]
min_diff = 10**6
for j in range(0, len(pentagonal)-1):
    for k in range(j+1, len(pentagonal)):
        #print(pentagonal[j], pentagonal[k])
        sum_p = pentagonal[j] + pentagonal[k]
        diff_p = pentagonal[k] - pentagonal[j]
        #print(sum_p, diff_p)
        if sum_p in pentagonal:
            #print('sum is pentagonal')
            if diff_p in pentagonal:
                print('diff also')
                print(diff_p)
                break   
print(min_diff)